name: balance_psy
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  vector_math: ^2.2.0

  youtube_player_flutter: ^8.1.2
  video_player: ^2.8.2
  flutter_svg: ^2.0.9

  date_format: ^2.0.8

  provider: ^6.1.1

  dio: ^5.0.0
  flutter_secure_storage: ^8.0.0
  flutter_riverpod: ^2.3.0
  form_field_validator: ^1.1.0
  url_launcher: ^6.3.2

  http: ^1.2.0
  
  shared_preferences: ^2.2.2
  
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.0
  json_serializable: ^6.6.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logopsy.svg
    - assets/images/meditation.png
    - assets/images/article/sad.png
    - assets/images/article/depressed.png
    - assets/images/article/love.png
    - assets/images/article/5min.png
    - assets/images/article/body.png
    - assets/images/article/sleep.png
    - assets/images/article/calm.png
    - assets/images/article/dontAgro.png
    - assets/images/article/empty.png
    - assets/images/article/evening.png
    - assets/images/article/firelove.png
    - assets/images/article/happy.png
    - assets/images/article/givesad.png
    - assets/images/article/sense.png
    - assets/images/article/whyIlove.png
    - assets/stepimages/step1.png
    - assets/stepimages/women.svg
    - assets/stepimages/men.svg
    - assets/images/mood/mood_overjoyed.png
    - assets/images/mood/mood_happy.png
    - assets/images/mood/mood_neutral.png
    - assets/images/mood/mood_sad.png
    - assets/images/mood/mood_depressed.png
    - assets/images/avatar/Galiya.png
    - assets/video/intro.mp4
    - assets/images/main_page/phone1.png
    - assets/images/main_page/features.svg 
    - assets/images/main_page/woman.svg
    - assets/images/main_page/features-2.png
    - assets/images/main_page/galiya1.png
    - assets/images/main_page/yana1.png
    - assets/images/main_page/laura1.png
    - assets/images/main_page/phone2.png
    - assets/images/avatar/aldiyar.png
    - assets/images/avatar/yana2.png
    - assets/images/avatar/laura2.png
    - assets/images/avatar/diana.png
    - assets/images/avatar/ainur.png
    - assets/images/avatar/aigerim.png
    - assets/menu_bar/article.png
    - assets/menu_bar/catalog.png
    - assets/menu_bar/home.png
    - assets/menu_bar/chat.png
    - assets/menu_bar/profile.png


  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Light.ttf
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 700